version: 0.1
phases:
 install:
   commands:
     - npm i
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - npm build
 post_build:
   commands:
     - aws s3 sync --delete . "s3://fly"